version: '3.4'
services:
  mongo:
    image: mongo:4.1
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME:admin"
      - "MONGO_INITDB_ROOT_PASSWORD:admin"
      - "MONGO_INITDB_DATABASE:users"
    volumes:
      - "./mongodata:/data/db"
      - "./mongoconfig:/data/configdb"
