spring:
  application:
    name: UserManagementService
  data:
    mongodb:
      host: ${MONGOHOST:192.168.99.100}
      port: ${MONGOPORT:27017}
      database: user
  devtools:
    restart:
      enabled: true
      
server:
  port: ${SERVER_PORT:1000}
  
#  servlet:
#    context-path: /v1/users
    
    