spring:
  application:
    name: UserManagementService
  data:
    mongodb:
      host: ${MONGOHOST:localhost}
      port: ${MONGOPORT:27017}
      database: user
  devtools:
    restart:
      enabled: true
      
server:
  port: ${SERVER_PORT:2000}
  servlet:
    context-path: /v1
    
