version: '3.6'
services:
  userservice:
    image: ps-userservice:01
    container_name: userservice
    ports:
      - "2000:2000"
    restart: always
    environment:
      - "MONGOHOST:192.168.99.100"
      - "MONGOPORT:27017"
    volumes:
#      - "../../.m2:/root/.m2"
#      - "/c/Users/Rob Paul Jr/.m2:/root/.m2"
      - "maven-repo:/root/.m2"
    build:
        context: ./UserManagementService
        dockerfile: Dockerfile
  mongo:
    image: mongo:4.1
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME:admin"
      - "MONGO_INITDB_ROOT_PASSWORD:admin"
      - "MONGO_INITDB_DATABASE:users"
## There is a problem with running docker on Windows, particular using something like VirtualBox.
## Need to explicitly define the volume mount in this file, outside of service definitions, then reference
## the docker volume 'mongodata' by name in the mongo service definition volume specs.       
## See - https://github.com/docker-library/mongo/issues/74
##       https://docs.mongodb.com/manual/administration/production-notes/#fsync-on-directories
    volumes:
      - "mongodata:/data/db"
      - "${PWD}/mongoconfig:/data/configdb"
volumes:
  mongodata:
  maven-repo:
#    external: true
